[2021-09-27 16:00:03,365] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: day1_challenge2.echo_hello 2021-09-27T15:50:00+00:00 [queued]>
[2021-09-27 16:00:03,447] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: day1_challenge2.echo_hello 2021-09-27T15:50:00+00:00 [queued]>
[2021-09-27 16:00:03,470] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 16:00:03,471] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-09-27 16:00:03,474] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 16:00:03,574] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): echo_hello> on 2021-09-27T15:50:00+00:00
[2021-09-27 16:00:03,590] {standard_task_runner.py:52} INFO - Started process 38982 to run task
[2021-09-27 16:00:03,616] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'day1_challenge2', 'echo_hello', '2021-09-27T15:50:00+00:00', '--job-id', '114', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/day1_challenge2.py', '--cfg-path', '/tmp/tmp_qi7nve1', '--error-file', '/tmp/tmpddwnnb99']
[2021-09-27 16:00:03,641] {standard_task_runner.py:77} INFO - Job 114: Subtask echo_hello
[2021-09-27 16:00:04,194] {logging_mixin.py:109} INFO - Running <TaskInstance: day1_challenge2.echo_hello 2021-09-27T15:50:00+00:00 [running]> on host 196580edc338
[2021-09-27 16:00:05,388] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Attasil Chitwirote
AIRFLOW_CTX_DAG_ID=day1_challenge2
AIRFLOW_CTX_TASK_ID=echo_hello
AIRFLOW_CTX_EXECUTION_DATE=2021-09-27T15:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-27T15:50:00+00:00
[2021-09-27 16:00:05,412] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-09-27 16:00:05,427] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'hello'"]
[2021-09-27 16:00:05,651] {subprocess.py:74} INFO - Output:
[2021-09-27 16:00:05,690] {subprocess.py:78} INFO - hello
[2021-09-27 16:00:05,693] {subprocess.py:82} INFO - Command exited with return code 0
[2021-09-27 16:00:05,822] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=day1_challenge2, task_id=echo_hello, execution_date=20210927T155000, start_date=20210927T160003, end_date=20210927T160005
[2021-09-27 16:00:06,049] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-27 16:00:06,201] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
